// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameBook = "books"

// Book mapped from table <books>
type Book struct {
	ID        uint64         `gorm:"column:id;type:bigint(20) unsigned;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt time.Time      `gorm:"column:created_at;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:datetime;index:idx_songs_deleted_at,priority:1" json:"deleted_at"`
	Title     string         `gorm:"column:title;type:varchar(200);not null;comment:书籍名称" json:"title"` // 书籍名称
	Author    string         `gorm:"column:author;type:varchar(200);not null;comment:专辑" json:"author"` // 专辑
	Genre     string         `gorm:"column:genre;type:varchar(200);not null;comment:专辑" json:"genre"`   // 专辑
}

// TableName Book's table name
func (*Book) TableName() string {
	return TableNameBook
}
