// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package music

import (
	"context"
	"fmt"
	"testing"

	"github.com/caiknife/mp3lister/orm/music/model"
	"gorm.io/gen"
	"gorm.io/gen/field"
	"gorm.io/gorm/clause"
)

func init() {
	InitializeDB()
	err := db.AutoMigrate(&model.Entry{})
	if err != nil {
		fmt.Printf("Error: AutoMigrate(&model.Entry{}) fail: %s", err)
	}
}

func Test_entryQuery(t *testing.T) {
	entry := newEntry(db)
	entry = *entry.As(entry.TableName())
	_do := entry.WithContext(context.Background()).Debug()

	primaryKey := field.NewString(entry.TableName(), clause.PrimaryKey)
	_, err := _do.Unscoped().Where(primaryKey.IsNotNull()).Delete()
	if err != nil {
		t.Error("clean table <entries> fail:", err)
		return
	}

	_, ok := entry.GetFieldByName("")
	if ok {
		t.Error("GetFieldByName(\"\") from entry success")
	}

	err = _do.Create(&model.Entry{})
	if err != nil {
		t.Error("create item in table <entries> fail:", err)
	}

	err = _do.Save(&model.Entry{})
	if err != nil {
		t.Error("create item in table <entries> fail:", err)
	}

	err = _do.CreateInBatches([]*model.Entry{{}, {}}, 10)
	if err != nil {
		t.Error("create item in table <entries> fail:", err)
	}

	_, err = _do.Select(entry.ALL).Take()
	if err != nil {
		t.Error("Take() on table <entries> fail:", err)
	}

	_, err = _do.First()
	if err != nil {
		t.Error("First() on table <entries> fail:", err)
	}

	_, err = _do.Last()
	if err != nil {
		t.Error("First() on table <entries> fail:", err)
	}

	_, err = _do.Where(primaryKey.IsNotNull()).FindInBatch(10, func(tx gen.Dao, batch int) error { return nil })
	if err != nil {
		t.Error("FindInBatch() on table <entries> fail:", err)
	}

	err = _do.Where(primaryKey.IsNotNull()).FindInBatches(&[]*model.Entry{}, 10, func(tx gen.Dao, batch int) error { return nil })
	if err != nil {
		t.Error("FindInBatches() on table <entries> fail:", err)
	}

	_, err = _do.Select(entry.ALL).Where(primaryKey.IsNotNull()).Order(primaryKey.Desc()).Find()
	if err != nil {
		t.Error("Find() on table <entries> fail:", err)
	}

	_, err = _do.Distinct(primaryKey).Take()
	if err != nil {
		t.Error("select Distinct() on table <entries> fail:", err)
	}

	_, err = _do.Select(entry.ALL).Omit(primaryKey).Take()
	if err != nil {
		t.Error("Omit() on table <entries> fail:", err)
	}

	_, err = _do.Group(primaryKey).Find()
	if err != nil {
		t.Error("Group() on table <entries> fail:", err)
	}

	_, err = _do.Scopes(func(dao gen.Dao) gen.Dao { return dao.Where(primaryKey.IsNotNull()) }).Find()
	if err != nil {
		t.Error("Scopes() on table <entries> fail:", err)
	}

	_, _, err = _do.FindByPage(0, 1)
	if err != nil {
		t.Error("FindByPage() on table <entries> fail:", err)
	}

	_, err = _do.ScanByPage(&model.Entry{}, 0, 1)
	if err != nil {
		t.Error("ScanByPage() on table <entries> fail:", err)
	}

	_, err = _do.Attrs(primaryKey).Assign(primaryKey).FirstOrInit()
	if err != nil {
		t.Error("FirstOrInit() on table <entries> fail:", err)
	}

	_, err = _do.Attrs(primaryKey).Assign(primaryKey).FirstOrCreate()
	if err != nil {
		t.Error("FirstOrCreate() on table <entries> fail:", err)
	}

	var _a _another
	var _aPK = field.NewString(_a.TableName(), "id")

	err = _do.Join(&_a, primaryKey.EqCol(_aPK)).Scan(map[string]interface{}{})
	if err != nil {
		t.Error("Join() on table <entries> fail:", err)
	}

	err = _do.LeftJoin(&_a, primaryKey.EqCol(_aPK)).Scan(map[string]interface{}{})
	if err != nil {
		t.Error("LeftJoin() on table <entries> fail:", err)
	}

	_, err = _do.Not().Or().Clauses().Take()
	if err != nil {
		t.Error("Not/Or/Clauses on table <entries> fail:", err)
	}
}
