// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package music

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/caiknife/mp3lister/orm/music/model"
)

func newEntry(db *gorm.DB, opts ...gen.DOOption) entry {
	_entry := entry{}

	_entry.entryDo.UseDB(db, opts...)
	_entry.entryDo.UseModel(&model.Entry{})

	tableName := _entry.entryDo.TableName()
	_entry.ALL = field.NewAsterisk(tableName)
	_entry.ID = field.NewUint64(tableName, "id")
	_entry.CreatedAt = field.NewTime(tableName, "created_at")
	_entry.UpdatedAt = field.NewTime(tableName, "updated_at")
	_entry.DeletedAt = field.NewField(tableName, "deleted_at")
	_entry.Title = field.NewString(tableName, "title")
	_entry.Artist = field.NewString(tableName, "artist")
	_entry.Album = field.NewString(tableName, "album")
	_entry.Bpm = field.NewInt32(tableName, "bpm")
	_entry.OriginFile = field.NewString(tableName, "origin_file")

	_entry.fillFieldMap()

	return _entry
}

type entry struct {
	entryDo

	ALL        field.Asterisk
	ID         field.Uint64
	CreatedAt  field.Time
	UpdatedAt  field.Time
	DeletedAt  field.Field
	Title      field.String // 歌曲名称
	Artist     field.String // 艺术家
	Album      field.String // 专辑
	Bpm        field.Int32  // BPM
	OriginFile field.String // 源文件路径

	fieldMap map[string]field.Expr
}

func (e entry) Table(newTableName string) *entry {
	e.entryDo.UseTable(newTableName)
	return e.updateTableName(newTableName)
}

func (e entry) As(alias string) *entry {
	e.entryDo.DO = *(e.entryDo.As(alias).(*gen.DO))
	return e.updateTableName(alias)
}

func (e *entry) updateTableName(table string) *entry {
	e.ALL = field.NewAsterisk(table)
	e.ID = field.NewUint64(table, "id")
	e.CreatedAt = field.NewTime(table, "created_at")
	e.UpdatedAt = field.NewTime(table, "updated_at")
	e.DeletedAt = field.NewField(table, "deleted_at")
	e.Title = field.NewString(table, "title")
	e.Artist = field.NewString(table, "artist")
	e.Album = field.NewString(table, "album")
	e.Bpm = field.NewInt32(table, "bpm")
	e.OriginFile = field.NewString(table, "origin_file")

	e.fillFieldMap()

	return e
}

func (e *entry) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := e.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (e *entry) fillFieldMap() {
	e.fieldMap = make(map[string]field.Expr, 9)
	e.fieldMap["id"] = e.ID
	e.fieldMap["created_at"] = e.CreatedAt
	e.fieldMap["updated_at"] = e.UpdatedAt
	e.fieldMap["deleted_at"] = e.DeletedAt
	e.fieldMap["title"] = e.Title
	e.fieldMap["artist"] = e.Artist
	e.fieldMap["album"] = e.Album
	e.fieldMap["bpm"] = e.Bpm
	e.fieldMap["origin_file"] = e.OriginFile
}

func (e entry) clone(db *gorm.DB) entry {
	e.entryDo.ReplaceConnPool(db.Statement.ConnPool)
	return e
}

func (e entry) replaceDB(db *gorm.DB) entry {
	e.entryDo.ReplaceDB(db)
	return e
}

type entryDo struct{ gen.DO }

func (e entryDo) Debug() *entryDo {
	return e.withDO(e.DO.Debug())
}

func (e entryDo) WithContext(ctx context.Context) *entryDo {
	return e.withDO(e.DO.WithContext(ctx))
}

func (e entryDo) ReadDB() *entryDo {
	return e.Clauses(dbresolver.Read)
}

func (e entryDo) WriteDB() *entryDo {
	return e.Clauses(dbresolver.Write)
}

func (e entryDo) Session(config *gorm.Session) *entryDo {
	return e.withDO(e.DO.Session(config))
}

func (e entryDo) Clauses(conds ...clause.Expression) *entryDo {
	return e.withDO(e.DO.Clauses(conds...))
}

func (e entryDo) Returning(value interface{}, columns ...string) *entryDo {
	return e.withDO(e.DO.Returning(value, columns...))
}

func (e entryDo) Not(conds ...gen.Condition) *entryDo {
	return e.withDO(e.DO.Not(conds...))
}

func (e entryDo) Or(conds ...gen.Condition) *entryDo {
	return e.withDO(e.DO.Or(conds...))
}

func (e entryDo) Select(conds ...field.Expr) *entryDo {
	return e.withDO(e.DO.Select(conds...))
}

func (e entryDo) Where(conds ...gen.Condition) *entryDo {
	return e.withDO(e.DO.Where(conds...))
}

func (e entryDo) Order(conds ...field.Expr) *entryDo {
	return e.withDO(e.DO.Order(conds...))
}

func (e entryDo) Distinct(cols ...field.Expr) *entryDo {
	return e.withDO(e.DO.Distinct(cols...))
}

func (e entryDo) Omit(cols ...field.Expr) *entryDo {
	return e.withDO(e.DO.Omit(cols...))
}

func (e entryDo) Join(table schema.Tabler, on ...field.Expr) *entryDo {
	return e.withDO(e.DO.Join(table, on...))
}

func (e entryDo) LeftJoin(table schema.Tabler, on ...field.Expr) *entryDo {
	return e.withDO(e.DO.LeftJoin(table, on...))
}

func (e entryDo) RightJoin(table schema.Tabler, on ...field.Expr) *entryDo {
	return e.withDO(e.DO.RightJoin(table, on...))
}

func (e entryDo) Group(cols ...field.Expr) *entryDo {
	return e.withDO(e.DO.Group(cols...))
}

func (e entryDo) Having(conds ...gen.Condition) *entryDo {
	return e.withDO(e.DO.Having(conds...))
}

func (e entryDo) Limit(limit int) *entryDo {
	return e.withDO(e.DO.Limit(limit))
}

func (e entryDo) Offset(offset int) *entryDo {
	return e.withDO(e.DO.Offset(offset))
}

func (e entryDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *entryDo {
	return e.withDO(e.DO.Scopes(funcs...))
}

func (e entryDo) Unscoped() *entryDo {
	return e.withDO(e.DO.Unscoped())
}

func (e entryDo) Create(values ...*model.Entry) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Create(values)
}

func (e entryDo) CreateInBatches(values []*model.Entry, batchSize int) error {
	return e.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (e entryDo) Save(values ...*model.Entry) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Save(values)
}

func (e entryDo) First() (*model.Entry, error) {
	if result, err := e.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Entry), nil
	}
}

func (e entryDo) Take() (*model.Entry, error) {
	if result, err := e.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Entry), nil
	}
}

func (e entryDo) Last() (*model.Entry, error) {
	if result, err := e.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Entry), nil
	}
}

func (e entryDo) Find() ([]*model.Entry, error) {
	result, err := e.DO.Find()
	return result.([]*model.Entry), err
}

func (e entryDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Entry, err error) {
	buf := make([]*model.Entry, 0, batchSize)
	err = e.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (e entryDo) FindInBatches(result *[]*model.Entry, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return e.DO.FindInBatches(result, batchSize, fc)
}

func (e entryDo) Attrs(attrs ...field.AssignExpr) *entryDo {
	return e.withDO(e.DO.Attrs(attrs...))
}

func (e entryDo) Assign(attrs ...field.AssignExpr) *entryDo {
	return e.withDO(e.DO.Assign(attrs...))
}

func (e entryDo) Joins(fields ...field.RelationField) *entryDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Joins(_f))
	}
	return &e
}

func (e entryDo) Preload(fields ...field.RelationField) *entryDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Preload(_f))
	}
	return &e
}

func (e entryDo) FirstOrInit() (*model.Entry, error) {
	if result, err := e.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Entry), nil
	}
}

func (e entryDo) FirstOrCreate() (*model.Entry, error) {
	if result, err := e.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Entry), nil
	}
}

func (e entryDo) FindByPage(offset int, limit int) (result []*model.Entry, count int64, err error) {
	result, err = e.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = e.Offset(-1).Limit(-1).Count()
	return
}

func (e entryDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = e.Count()
	if err != nil {
		return
	}

	err = e.Offset(offset).Limit(limit).Scan(result)
	return
}

func (e entryDo) Scan(result interface{}) (err error) {
	return e.DO.Scan(result)
}

func (e entryDo) Delete(models ...*model.Entry) (result gen.ResultInfo, err error) {
	return e.DO.Delete(models)
}

func (e *entryDo) withDO(do gen.Dao) *entryDo {
	e.DO = *do.(*gen.DO)
	return e
}
