// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package music

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q      = new(Query)
	Book   *book
	Car    *car
	Movie  *movie
	Player *player
	Song   *song
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	Book = &Q.Book
	Car = &Q.Car
	Movie = &Q.Movie
	Player = &Q.Player
	Song = &Q.Song
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:     db,
		Book:   newBook(db, opts...),
		Car:    newCar(db, opts...),
		Movie:  newMovie(db, opts...),
		Player: newPlayer(db, opts...),
		Song:   newSong(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Book   book
	Car    car
	Movie  movie
	Player player
	Song   song
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:     db,
		Book:   q.Book.clone(db),
		Car:    q.Car.clone(db),
		Movie:  q.Movie.clone(db),
		Player: q.Player.clone(db),
		Song:   q.Song.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:     db,
		Book:   q.Book.replaceDB(db),
		Car:    q.Car.replaceDB(db),
		Movie:  q.Movie.replaceDB(db),
		Player: q.Player.replaceDB(db),
		Song:   q.Song.replaceDB(db),
	}
}

type queryCtx struct {
	Book   *bookDo
	Car    *carDo
	Movie  *movieDo
	Player *playerDo
	Song   *songDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Book:   q.Book.WithContext(ctx),
		Car:    q.Car.WithContext(ctx),
		Movie:  q.Movie.WithContext(ctx),
		Player: q.Player.WithContext(ctx),
		Song:   q.Song.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
