// Code generated by "stringer -type BizCode -linecomment"; DO NOT EDIT.

package enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BizCodeOK-0]
	_ = x[BizCodeFail-1]
	_ = x[BizCodeTimeout-2]
}

const _BizCode_name = "正常失败超时"

var _BizCode_index = [...]uint8{0, 6, 12, 18}

func (i BizCode) String() string {
	if i < 0 || i >= BizCode(len(_BizCode_index)-1) {
		return "BizCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _BizCode_name[_BizCode_index[i]:_BizCode_index[i+1]]
}
