// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package wartankcn

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/caiknife/mp3lister/orm/wartankcn/model"
)

func newWtSocial(db *gorm.DB, opts ...gen.DOOption) wtSocial {
	_wtSocial := wtSocial{}

	_wtSocial.wtSocialDo.UseDB(db, opts...)
	_wtSocial.wtSocialDo.UseModel(&model.WtSocial{})

	tableName := _wtSocial.wtSocialDo.TableName()
	_wtSocial.ALL = field.NewAsterisk(tableName)
	_wtSocial.ID = field.NewString(tableName, "id")
	_wtSocial.PlayerID = field.NewInt64(tableName, "player_id")
	_wtSocial.SocialType = field.NewInt32(tableName, "social_type")
	_wtSocial.CreateTime = field.NewTime(tableName, "create_time")
	_wtSocial.UpdateTime = field.NewTime(tableName, "update_time")

	_wtSocial.fillFieldMap()

	return _wtSocial
}

// wtSocial 玩家与社交账号绑定信息表
type wtSocial struct {
	wtSocialDo

	ALL        field.Asterisk
	ID         field.String // 社交账号ID
	PlayerID   field.Int64  // 玩家ID
	SocialType field.Int32  // 社交账号类型
	CreateTime field.Time   // 创建时间
	UpdateTime field.Time   // 更新时间

	fieldMap map[string]field.Expr
}

func (w wtSocial) Table(newTableName string) *wtSocial {
	w.wtSocialDo.UseTable(newTableName)
	return w.updateTableName(newTableName)
}

func (w wtSocial) As(alias string) *wtSocial {
	w.wtSocialDo.DO = *(w.wtSocialDo.As(alias).(*gen.DO))
	return w.updateTableName(alias)
}

func (w *wtSocial) updateTableName(table string) *wtSocial {
	w.ALL = field.NewAsterisk(table)
	w.ID = field.NewString(table, "id")
	w.PlayerID = field.NewInt64(table, "player_id")
	w.SocialType = field.NewInt32(table, "social_type")
	w.CreateTime = field.NewTime(table, "create_time")
	w.UpdateTime = field.NewTime(table, "update_time")

	w.fillFieldMap()

	return w
}

func (w *wtSocial) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := w.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (w *wtSocial) fillFieldMap() {
	w.fieldMap = make(map[string]field.Expr, 5)
	w.fieldMap["id"] = w.ID
	w.fieldMap["player_id"] = w.PlayerID
	w.fieldMap["social_type"] = w.SocialType
	w.fieldMap["create_time"] = w.CreateTime
	w.fieldMap["update_time"] = w.UpdateTime
}

func (w wtSocial) clone(db *gorm.DB) wtSocial {
	w.wtSocialDo.ReplaceConnPool(db.Statement.ConnPool)
	return w
}

func (w wtSocial) replaceDB(db *gorm.DB) wtSocial {
	w.wtSocialDo.ReplaceDB(db)
	return w
}

type wtSocialDo struct{ gen.DO }

func (w wtSocialDo) Debug() *wtSocialDo {
	return w.withDO(w.DO.Debug())
}

func (w wtSocialDo) WithContext(ctx context.Context) *wtSocialDo {
	return w.withDO(w.DO.WithContext(ctx))
}

func (w wtSocialDo) ReadDB() *wtSocialDo {
	return w.Clauses(dbresolver.Read)
}

func (w wtSocialDo) WriteDB() *wtSocialDo {
	return w.Clauses(dbresolver.Write)
}

func (w wtSocialDo) Session(config *gorm.Session) *wtSocialDo {
	return w.withDO(w.DO.Session(config))
}

func (w wtSocialDo) Clauses(conds ...clause.Expression) *wtSocialDo {
	return w.withDO(w.DO.Clauses(conds...))
}

func (w wtSocialDo) Returning(value interface{}, columns ...string) *wtSocialDo {
	return w.withDO(w.DO.Returning(value, columns...))
}

func (w wtSocialDo) Not(conds ...gen.Condition) *wtSocialDo {
	return w.withDO(w.DO.Not(conds...))
}

func (w wtSocialDo) Or(conds ...gen.Condition) *wtSocialDo {
	return w.withDO(w.DO.Or(conds...))
}

func (w wtSocialDo) Select(conds ...field.Expr) *wtSocialDo {
	return w.withDO(w.DO.Select(conds...))
}

func (w wtSocialDo) Where(conds ...gen.Condition) *wtSocialDo {
	return w.withDO(w.DO.Where(conds...))
}

func (w wtSocialDo) Order(conds ...field.Expr) *wtSocialDo {
	return w.withDO(w.DO.Order(conds...))
}

func (w wtSocialDo) Distinct(cols ...field.Expr) *wtSocialDo {
	return w.withDO(w.DO.Distinct(cols...))
}

func (w wtSocialDo) Omit(cols ...field.Expr) *wtSocialDo {
	return w.withDO(w.DO.Omit(cols...))
}

func (w wtSocialDo) Join(table schema.Tabler, on ...field.Expr) *wtSocialDo {
	return w.withDO(w.DO.Join(table, on...))
}

func (w wtSocialDo) LeftJoin(table schema.Tabler, on ...field.Expr) *wtSocialDo {
	return w.withDO(w.DO.LeftJoin(table, on...))
}

func (w wtSocialDo) RightJoin(table schema.Tabler, on ...field.Expr) *wtSocialDo {
	return w.withDO(w.DO.RightJoin(table, on...))
}

func (w wtSocialDo) Group(cols ...field.Expr) *wtSocialDo {
	return w.withDO(w.DO.Group(cols...))
}

func (w wtSocialDo) Having(conds ...gen.Condition) *wtSocialDo {
	return w.withDO(w.DO.Having(conds...))
}

func (w wtSocialDo) Limit(limit int) *wtSocialDo {
	return w.withDO(w.DO.Limit(limit))
}

func (w wtSocialDo) Offset(offset int) *wtSocialDo {
	return w.withDO(w.DO.Offset(offset))
}

func (w wtSocialDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *wtSocialDo {
	return w.withDO(w.DO.Scopes(funcs...))
}

func (w wtSocialDo) Unscoped() *wtSocialDo {
	return w.withDO(w.DO.Unscoped())
}

func (w wtSocialDo) Create(values ...*model.WtSocial) error {
	if len(values) == 0 {
		return nil
	}
	return w.DO.Create(values)
}

func (w wtSocialDo) CreateInBatches(values []*model.WtSocial, batchSize int) error {
	return w.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (w wtSocialDo) Save(values ...*model.WtSocial) error {
	if len(values) == 0 {
		return nil
	}
	return w.DO.Save(values)
}

func (w wtSocialDo) First() (*model.WtSocial, error) {
	if result, err := w.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.WtSocial), nil
	}
}

func (w wtSocialDo) Take() (*model.WtSocial, error) {
	if result, err := w.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.WtSocial), nil
	}
}

func (w wtSocialDo) Last() (*model.WtSocial, error) {
	if result, err := w.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.WtSocial), nil
	}
}

func (w wtSocialDo) Find() ([]*model.WtSocial, error) {
	result, err := w.DO.Find()
	return result.([]*model.WtSocial), err
}

func (w wtSocialDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.WtSocial, err error) {
	buf := make([]*model.WtSocial, 0, batchSize)
	err = w.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (w wtSocialDo) FindInBatches(result *[]*model.WtSocial, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return w.DO.FindInBatches(result, batchSize, fc)
}

func (w wtSocialDo) Attrs(attrs ...field.AssignExpr) *wtSocialDo {
	return w.withDO(w.DO.Attrs(attrs...))
}

func (w wtSocialDo) Assign(attrs ...field.AssignExpr) *wtSocialDo {
	return w.withDO(w.DO.Assign(attrs...))
}

func (w wtSocialDo) Joins(fields ...field.RelationField) *wtSocialDo {
	for _, _f := range fields {
		w = *w.withDO(w.DO.Joins(_f))
	}
	return &w
}

func (w wtSocialDo) Preload(fields ...field.RelationField) *wtSocialDo {
	for _, _f := range fields {
		w = *w.withDO(w.DO.Preload(_f))
	}
	return &w
}

func (w wtSocialDo) FirstOrInit() (*model.WtSocial, error) {
	if result, err := w.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.WtSocial), nil
	}
}

func (w wtSocialDo) FirstOrCreate() (*model.WtSocial, error) {
	if result, err := w.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.WtSocial), nil
	}
}

func (w wtSocialDo) FindByPage(offset int, limit int) (result []*model.WtSocial, count int64, err error) {
	result, err = w.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = w.Offset(-1).Limit(-1).Count()
	return
}

func (w wtSocialDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = w.Count()
	if err != nil {
		return
	}

	err = w.Offset(offset).Limit(limit).Scan(result)
	return
}

func (w wtSocialDo) Scan(result interface{}) (err error) {
	return w.DO.Scan(result)
}

func (w wtSocialDo) Delete(models ...*model.WtSocial) (result gen.ResultInfo, err error) {
	return w.DO.Delete(models)
}

func (w *wtSocialDo) withDO(do gen.Dao) *wtSocialDo {
	w.DO = *do.(*gen.DO)
	return w
}
