// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameSong = "songs"

// Song mapped from table <songs>
type Song struct {
	ID         int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt  time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt  time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt  gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	Title      string         `gorm:"column:title;not null" json:"title"`             // 歌曲名称
	Artist     string         `gorm:"column:artist;not null" json:"artist"`           // 艺术家
	Album      string         `gorm:"column:album;not null" json:"album"`             // 专辑
	Bpm        string         `gorm:"column:bpm;not null" json:"bpm"`                 // BPM
	OriginFile string         `gorm:"column:origin_file;not null" json:"origin_file"` // 源文件路径
}

// TableName Song's table name
func (*Song) TableName() string {
	return TableNameSong
}
