// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameChargeRefund = "charge_refund"

// ChargeRefund mapped from table <charge_refund>
type ChargeRefund struct {
	ID           uint64         `gorm:"column:id;type:bigint unsigned;primaryKey" json:"id"`
	GameCenterID string         `gorm:"column:game_center_id;type:varchar(255);not null;index:game_center_id,priority:1" json:"game_center_id"`
	PlayerID     int64          `gorm:"column:player_id;type:bigint;not null;index:player_id,priority:1" json:"player_id"`
	TotalCharge  float64        `gorm:"column:total_charge;type:double;not null" json:"total_charge"`
	Diamonds     int64          `gorm:"column:diamonds;type:bigint;not null" json:"diamonds"`
	Acquired     bool           `gorm:"column:acquired;type:tinyint(1);not null" json:"acquired"`
	CreatedAt    time.Time      `gorm:"column:created_at;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt    time.Time      `gorm:"column:updated_at;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt    gorm.DeletedAt `gorm:"column:deleted_at;type:datetime" json:"deleted_at"`
}

// TableName ChargeRefund's table name
func (*ChargeRefund) TableName() string {
	return TableNameChargeRefund
}
