// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameWtDevice = "wt_device"

// WtDevice 玩家设备关系表
type WtDevice struct {
	ID           string    `gorm:"column:id;type:varchar(60);primaryKey;comment:设备ID" json:"id"`                                           // 设备ID
	PlayerID     int64     `gorm:"column:player_id;type:bigint(20);not null;comment:玩家ID" json:"player_id"`                                // 玩家ID
	DeviceRegion string    `gorm:"column:device_region;type:varchar(5);not null;comment:设备地区" json:"device_region"`                        // 设备地区
	CreateTime   time.Time `gorm:"column:create_time;type:timestamp;not null;default:current_timestamp();comment:创建时间" json:"create_time"` // 创建时间
	UpdateTime   time.Time `gorm:"column:update_time;type:timestamp;not null;default:current_timestamp();comment:更新时间" json:"update_time"` // 更新时间
}

// TableName WtDevice's table name
func (*WtDevice) TableName() string {
	return TableNameWtDevice
}
