// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/datatypes"
)

const TableNameWtLegion = "wt_legion"

// WtLegion 军团表
type WtLegion struct {
	ID           uint64         `gorm:"column:id;type:bigint(20) unsigned;primaryKey;autoIncrement:true;comment:军团ID" json:"id"`                   // 军团ID
	Tag          string         `gorm:"column:tag;type:varchar(10);not null;uniqueIndex:tag,priority:1;comment:8位简码" json:"tag"`                   // 8位简码
	LegionName   string         `gorm:"column:legion_name;type:varchar(100);not null;index:legion_name,priority:1;comment:军团名" json:"legion_name"` // 军团名
	LegionBanner datatypes.JSON `gorm:"column:legion_banner;type:longtext;comment:军团旗帜" json:"legion_banner"`                                      // 军团旗帜
	Slogan       string         `gorm:"column:slogan;type:varchar(500);not null;comment:标语" json:"slogan"`                                         // 标语
	LimitTrophy  int32          `gorm:"column:limit_trophy;type:int(11);not null;comment:奖杯限制" json:"limit_trophy"`                                // 奖杯限制
	LimitWeek    int32          `gorm:"column:limit_week;type:int(11);not null;default:12;comment:周数限制" json:"limit_week"`                         // 周数限制
	Members      datatypes.JSON `gorm:"column:members;type:longtext;not null;comment:成员" json:"members"`                                           // 成员
	OpenLvl      int32          `gorm:"column:open_lvl;type:tinyint(4);not null;comment:开放级别" json:"open_lvl"`                                     // 开放级别
	TrophyScore  int32          `gorm:"column:trophy_score;type:int(11);not null;comment:奖杯分" json:"trophy_score"`                                 // 奖杯分
	CreateTime   time.Time      `gorm:"column:create_time;type:timestamp;not null;default:current_timestamp();comment:创建时间" json:"create_time"`    // 创建时间
	UpdateTime   time.Time      `gorm:"column:update_time;type:timestamp;not null;default:current_timestamp();comment:更新时间" json:"update_time"`    // 更新时间
	Version      int64          `gorm:"column:version;type:bigint(20);not null;comment:版本锁" json:"version"`                                        // 版本锁
	WarScore     int32          `gorm:"column:war_score;type:int(11);not null;comment:军团战分数" json:"war_score"`                                     // 军团战分数
	JoinWar      int32          `gorm:"column:join_war;type:tinyint(4);not null;comment:是否加入军团战" json:"join_war"`                                  // 是否加入军团战
	TankNumLimit int32          `gorm:"column:tank_num_limit;type:tinyint(4);not null;comment:加入军团的坦克限制" json:"tank_num_limit"`                    // 加入军团的坦克限制
}

// TableName WtLegion's table name
func (*WtLegion) TableName() string {
	return TableNameWtLegion
}
