// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameWtOrder = "wt_order"

// WtOrder 订单表
type WtOrder struct {
	ID          string    `gorm:"column:id;type:varchar(64);primaryKey;comment:订单ID" json:"id"`                                         // 订单ID
	PlayerID    int64     `gorm:"column:player_id;type:bigint;not null;index:player_id,priority:1;comment:玩家ID" json:"player_id"`       // 玩家ID
	BundleID    string    `gorm:"column:bundle_id;type:varchar(64);not null;comment:BUNDLE ID" json:"bundle_id"`                        // BUNDLE ID
	OrderStatus int32     `gorm:"column:order_status;type:tinyint;not null;comment:订单类型" json:"order_status"`                           // 订单类型
	ProductID   string    `gorm:"column:product_id;type:varchar(64);not null;comment:产品ID" json:"product_id"`                           // 产品ID
	PayType     int32     `gorm:"column:pay_type;type:tinyint;not null;comment:支付类型" json:"pay_type"`                                   // 支付类型
	CreateTime  time.Time `gorm:"column:create_time;type:timestamp;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time"` // 创建时间
	UpdateTime  time.Time `gorm:"column:update_time;type:timestamp;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"update_time"` // 更新时间
	TransID     string    `gorm:"column:trans_id;type:varchar(512);index:trans_id,priority:1;comment:交易ID" json:"trans_id"`             // 交易ID
	OrderInfo   string    `gorm:"column:order_info;type:text;comment:订单信息" json:"order_info"`                                           // 订单信息
	RewardInfo  string    `gorm:"column:reward_info;type:varchar(512);comment:奖励信息" json:"reward_info"`                                 // 奖励信息
	Version     int64     `gorm:"column:version;type:bigint;comment:数据版本" json:"version"`                                               // 数据版本
}

// TableName WtOrder's table name
func (*WtOrder) TableName() string {
	return TableNameWtOrder
}
